"""
The Swift Dictionary — Album & song metadata.

Central reference for every Taylor Swift album/song to be scraped.
The pipeline uses this list to query Genius and process lyrics.
"""

ALBUMS = [
    {
        "slug": "debut",
        "title": "Taylor Swift",
        "year": 2006,
        "description": "The beginning of Taylor's storytelling journey",
        "songs": [
            "Tim McGraw",
            "Picture to Burn",
            "Teardrops on My Guitar",
            "A Place in This World",
            "Cold as You",
            "The Outside",
            "Tied Together with a Smile",
            "Stay Beautiful",
            "Should've Said No",
            "Mary's Song (Oh My My My)",
            "Our Song",
        ],
    },
    {
        "slug": "fearless",
        "title": "Fearless",
        "year": 2008,
        "description": "Country-pop perfection with sophisticated vocabulary",
        "songs": [
            "Fearless",
            "Fifteen",
            "Love Story",
            "Hey Stephen",
            "White Horse",
            "You Belong with Me",
            "Breathe",
            "Tell Me Why",
            "You're Not Sorry",
            "The Way I Loved You",
            "Forever & Always",
            "The Best Day",
            "Change",
        ],
    },
    {
        "slug": "speaknow",
        "title": "Speak Now",
        "year": 2010,
        "description": "Self-written masterpiece with poetic language",
        "songs": [
            "Mine",
            "Sparks Fly",
            "Back to December",
            "Speak Now",
            "Dear John",
            "Mean",
            "The Story of Us",
            "Never Grow Up",
            "Enchanted",
            "Better than Revenge",
            "Innocent",
            "Haunted",
            "Last Kiss",
            "Long Live",
        ],
    },
    {
        "slug": "red",
        "title": "Red",
        "year": 2012,
        "description": "The transition era with emotional depth",
        "songs": [
            "State of Grace",
            "Red",
            "Treacherous",
            "I Knew You Were Trouble",
            "All Too Well",
            "22",
            "I Almost Do",
            "We Are Never Ever Getting Back Together",
            "Stay Stay Stay",
            "The Last Time",
            "Holy Ground",
            "Sad Beautiful Tragic",
            "The Lucky One",
            "Everything Has Changed",
            "Starlight",
            "Begin Again",
        ],
    },
    {
        "slug": "1989",
        "title": "1989",
        "year": 2014,
        "description": "Pop perfection with clever wordplay",
        "songs": [
            "Welcome to New York",
            "Blank Space",
            "Style",
            "Out of the Woods",
            "All You Had to Do Was Stay",
            "Shake It Off",
            "I Wish You Would",
            "Bad Blood",
            "Wildest Dreams",
            "How You Get the Girl",
            "This Love",
            "I Know Places",
            "Clean",
        ],
    },
    {
        "slug": "reputation",
        "title": "Reputation",
        "year": 2017,
        "description": "Dark pop with sophisticated storytelling",
        "songs": [
            "...Ready for It?",
            "End Game",
            "I Did Something Bad",
            "Don't Blame Me",
            "Delicate",
            "Look What You Made Me Do",
            "So It Goes...",
            "Gorgeous",
            "Getaway Car",
            "King of My Heart",
            "Dancing with Our Hands Tied",
            "Dress",
            "This Is Why We Can't Have Nice Things",
            "Call It What You Want",
            "New Year's Day",
        ],
    },
    {
        "slug": "lover",
        "title": "Lover",
        "year": 2019,
        "description": "Romantic pop with dreamy vocabulary",
        "songs": [
            "I Forgot That You Existed",
            "Cruel Summer",
            "Lover",
            "The Man",
            "The Archer",
            "I Think He Knows",
            "Miss Americana & the Heartbreak Prince",
            "Paper Rings",
            "Cornelia Street",
            "Death by a Thousand Cuts",
            "London Boy",
            "Soon You'll Get Better",
            "False God",
            "You Need to Calm Down",
            "Afterglow",
            "ME!",
            "It's Nice to Have a Friend",
            "Daylight",
        ],
    },
    {
        "slug": "folklore",
        "title": "Folklore",
        "year": 2020,
        "description": "Indie folk with literary sophistication",
        "songs": [
            "the 1",
            "cardigan",
            "the last great american dynasty",
            "exile",
            "my tears ricochet",
            "mirrorball",
            "seven",
            "august",
            "this is me trying",
            "illicit affairs",
            "invisible string",
            "mad woman",
            "epiphany",
            "betty",
            "peace",
            "hoax",
        ],
    },
    {
        "slug": "evermore",
        "title": "Evermore",
        "year": 2020,
        "description": "Sister album with rich storytelling",
        "songs": [
            "willow",
            "champagne problems",
            "gold rush",
            "'tis the damn season",
            "tolerate it",
            "no body, no crime",
            "happiness",
            "dorothea",
            "coney island",
            "ivy",
            "cowboy like me",
            "long story short",
            "marjorie",
            "closure",
            "evermore",
        ],
    },
    {
        "slug": "midnights",
        "title": "Midnights",
        "year": 2022,
        "description": "Late-night introspection with poetic depth",
        "songs": [
            "Lavender Haze",
            "Maroon",
            "Anti-Hero",
            "Snow on the Beach",
            "You're on Your Own, Kid",
            "Midnight Rain",
            "Question...?",
            "Vigilante Shit",
            "Bejeweled",
            "Labyrinth",
            "Karma",
            "Sweet Nothing",
            "Mastermind",
        ],
    },
    {
        "slug": "ttpd",
        "title": "The Tortured Poets Department",
        "year": 2024,
        "description": "Heartbreak anthology with raw confessional poetry",
        "songs": [
            "Fortnight",
            "The Tortured Poets Department",
            "My Boy Only Breaks His Favorite Toys",
            "Down Bad",
            "So Long, London",
            "But Daddy I Love Him",
            "Fresh Out the Slammer",
            "Florida!!!",
            "Guilty as Sin?",
            "Who's Afraid of Little Old Me?",
            "I Can Fix Him (No Really I Can)",
            "loml",
            "I Can Do It with a Broken Heart",
            "The Smallest Man Who Ever Lived",
            "The Alchemy",
            "Clara Bow",
            "The Black Dog",
            "imgonnagetyouback",
            "The Albatross",
            "Chloe or Sam or Sophia or Marcus",
            "How Did It End?",
            "So High School",
            "I Hate It Here",
            "Thank You Aimee",
            "I Look in People's Windows",
            "The Prophecy",
            "Cassandra",
            "Peter",
            "The Bolter",
            "Robin",
            "The Manuscript",
        ],
    },
    {
        "slug": "showgirl",
        "title": "The Life of a Showgirl",
        "year": 2025,
        "description": "Vibrant pop celebrating fame and love with showgirl flair",
        "songs": [
            "The Fate of Ophelia",
            "Elizabeth Taylor",
            "Opalite",
            "Father Figure",
            "Eldest Daughter",
            "Ruin the Friendship",
            "Actually Romantic",
            "Wish List",
            "Wood",
            "Cancelled!",
            "Honey",
            "The Life of a Showgirl",
        ],
    },
]
